# 公共配置文件
spring:
  application:
    name: springboot
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/access
    username: root
    password: root
  # Redis 配置
  # todo 需替换配置，然后取消注释
#  redis:
#    database: 1
#    host: localhost
#    port: 6379
#    timeout: 5000
#    password: 123456
  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
  elasticsearch:
    uris: http://localhost:9200
    username: root
    password: root
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8102
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 微信相关
wx:
  # 微信公众平台
  # todo 需替换配置
  mp:
    token: xxx
    aesKey: xxx
    appId: xxx
    secret: xxx
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  # 微信开放平台
  # todo 需替换配置
  open:
    appId: xxx
    appSecret: xxx
# 对象存储
# todo 需替换配置
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx
# emo值情感范围
emo:
  keyEmo:
    value: 20
    step: 5
  picEmo:
    value: 20
    step: 20
  emo:
    value: 30
    step: 2
# bilibili请求地址
bilibili:
  address: https://api.bilibili.com/x/web-interface/wbi/search/all/v2?__refresh__=true&_extra=&context=&page=1&page_size=42&order=&duration=&from_source=&from_spmid=333.337&platform=pc&highlight=1&single_column=0&keyword=刀&qv_id=I08EjPHKeK8FudM6nZZd0TtVe6dHIxES&ad_resource=5646&source_tag=3&web_location=1430654&w_rid=3eef9d0fde58433f2bff90f5422ab6d1&wts=1716886663
  Cookie: buvid3=9F96113C-D10F-E69D-992E-CC533CA7F11124688infoc; b_nut=1703762824; _uuid=F8A15FB3-3779-B995-B4A9-8C9EBE5BBEF124835infoc; buvid4=BEFEB271-B51C-5C25-E9F1-25A0F4DCA38925547-023122811-9sM4r%2F884bff%2FJM%2BeuQf7w%3D%3D; rpdid=|(k|JukRlm~k0J'u~|J~Yk)kY; buvid_fp_plain=undefined; enable_web_push=DISABLE; header_theme_version=CLOSE; hit-dyn-v2=1; LIVE_BUVID=AUTO3517044579065936; CURRENT_BLACKGAP=0; FEED_LIVE_VERSION=V_HEADER_LIVE_NEW_POP; CURRENT_QUALITY=127; bp_video_offset_58803854=931702174840258692; CURRENT_FNVAL=4048; PVID=7; bili_ticket=eyJhbGciOiJIUzI1NiIsImtpZCI6InMwMyIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTcxMzU4MzQsImlhdCI6MTcxNjg3NjU3NCwicGx0IjotMX0.OEz6LDriwc50YOa8PVi_8mOwQ8KeCesRmq3E3DeuQws; bili_ticket_expires=1717135774; home_feed_column=5; browser_resolution=1528-716; bsource=search_bing; fingerprint=68548d7a35938ef250e5bef1f9d6f9b8; b_lsid=CFC8214D_18FBE24B991; buvid_fp=68548d7a35938ef250e5bef1f9d6f9b8; sid=5n27bg1r; bp_t_offset_58803854=936497789032988674
